login/urls.py
from django.contrib import admin
from django.urls import path, include  # Added include module
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    path('admin/', admin.site.urls),  # Django-Admin
    path('', include('account.urls')),  # Added account app
    path('passwordGenerator/', include('passwordGenerator.urls'), name='passwordGenerator'),  # Added passwords app
    path('userprofile/', include('userprofile.urls'), name='userprofile'),
    path('monitor/', include('monitor.urls'), name='monitor')

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

passwordGenerator/urls.py
from django.urls import path
from . import views
app_name = 'passwordGenerator'
urlpatterns = [
    # Password Generator URLs
    path('choosepassword', views.passhome, name='passhome'),
    path('generatedpassword/', views.password, name='password'),
]

passwordGenerator/models.py
from django.db import models

# Create your models here.

passwordGenerator/views.py
from django.shortcuts import render
import pyperclip
import random


# Create your views here.
def passhome(request):
    return render(request, 'passwordGenerator/passhome.html')


def password(request):

    characters = list('abcdefghijklmnopqrstuvwxyz')
    if request.GET.get('uppercase'):
        characters.extend(list('ABCDEFGHIJKLMNOPQRSTUVWXYZ'))
    if request.GET.get('numbers'):
        characters.extend(list('0123456789'))
    if request.GET.get('special'):
        characters.extend(list(r'!@#$%^&*<>?-_:'))

    length = int(request.GET.get('length', 12))
    thepassword = ''
    for x in range(length):
        thepassword += random.choice(characters)
    pyperclip.copy(thepassword)
    return render(request, 'passwordGenerator/password.html', {'password': thepassword})

templates/passwordGenerator/passhome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!--Required meta tags -->
    <meta charset="UTF-8">
    <meta name ="viewport" content="width=device-width, initial-scale=1">
    <!---------------BOOTSTRAP 4--------------->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Generate Password</title>
</head>
<body>
<div class="container text-center m-5">
<h1 class="display-4">Generate a secure password</h1>
<form class="mt-3" action ="{% url 'passwordGenerator:password' %}">
    <select name = "length">
        <option value = "6">Six</option>
        <option value = "7">Seven</option>
        <option value = "8">Eight</option>
        <option value = "9">Nine</option>
        <option value = "10">Ten</option>
        <option value = "11">Eleven</option>
        <option value = "12" selected="selected">Twelve</option>
        <option value = "13">Thirteen</option>
        <option value = "14">Fourteen</option>
        <option value = "15">Fifteen</option>
    </select> Length
    <br>
    <input class="mt-3" type = "checkbox" name ="uppercase">&nbsp; Uppercase
    <br>
    <input class="mt-3" type = "checkbox" name ="numbers">&nbsp; Numbers
    <br>
    <input class="mt-2" type = "checkbox" name ="special">&nbsp; Special Characters
    <br>
    <input type = "submit" value ="Generate Password" class="mt-3 btn btn-primary">

</form>

</div>
<br>

</body>
</html>

templates/passwordGenerator/password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width , intial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <title>Generate Password</title>
</head>
<body>
<div class="container text-center mt-5">
    <h1 class="display-6">Your password is:</h1>
    <h2 class="alert alert-warning">{{password}}</h2>
    <div class="mt-3">
        <p class="lead">Just click on the password twice to automatically copy to clipboard!</p>
        <a class="btn btn-info" role="button" href="{% url 'passwordGenerator:passhome' %}">Back to generate password</a><br>
        <a class="mt-3 btn btn-secondary" role="button" href="{% url 'signupuser' %}">Back to Signup</a>

    </div>
    <br>

</div>
</body>
</html>