login/urls.py
from django.contrib import admin
from django.urls import path, include  # Added include module
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    path('admin/', admin.site.urls),  # Django-Admin
    path('', include('account.urls')),  # Added account app
    path('passwordGenerator/', include('passwordGenerator.urls'), name='passwordGenerator'),  # Added passwords app
    path('userprofile/', include('userprofile.urls'), name='userprofile'),
    path('monitor/', include('monitor.urls'), name='monitor')

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

monitor/urls.py
# În monitor/urls.py
from django.urls import path
from .views import monitorizare_retea
from monitor import views
from monitor import bgp_monitor
from pathlib import Path
from .bgp_stats import get_unique_prefixes
from .cpu_memory import get_router_stats


app_name = 'monitor'

urlpatterns = [
    path('monitor/', monitorizare_retea, name='monitor'),
    path('monitor', views.monitor, name="monitor"),
    path('salveaza-datele/', views.salveaza_datele, name='salveaza_datele'),
    path('show-routers-details/', views.show_routers_details, name='show_routers_details'),
    path('delete-router/', views.delete_router, name='delete_router'),
    path('router-statistics/<str:router_id>/', views.router_statistics, name='router_statistics'),
    path('router_cpu_mem/<str:router_id>/', get_router_stats, name='router_stats'),
    path('router_details/<str:router_id>/', views.router_details, name='router_details'),
    path('bgp-stats/', views.bgp_stats, name='bgp_stats'),
    path('rpki-servers-stats/', views.rpki_servers_stats, name='rpki-servers-stats'),
    path('api/get-bgp-stats/', views.get_bgp_stats, name='get_bgp_stats'),
    path('api/get-unique-prefixes/', get_unique_prefixes, name='get_unique_prefixes'),
    path('router_status/<str:router_id>/', views.router_uptime, name='router_uptime'),
    path('modify-router/', views.modify_router, name='modify_router'),
    path('rpki-data/', views.fetch_rpki_data, name='fetch_rpki_data'),
    path('configure_rpki/', views.configure_rpki, name='configure_rpki'),
    path('check_rpki/', views.check_rpki, name='check_rpki'),
    path('configure_rpki/', views.configure_rpki, name='configure_rpki'),
    path('get_router_asn/', views.get_router_asn, name='get_router_asn'),
    path('get_unread_alerts_count/', views.get_unread_alerts_count, name='get_unread_alerts_count'),
    path('get_alerts/', views.get_alerts, name='get_alerts'),
    path('mark_alerts_as_read/', views.mark_alerts_as_read, name='mark_alerts_as_read'),
    path('alerts/', views.alerts_page, name='alerts_page'),
    path('get_routes/', bgp_monitor.get_routes, name='get_routes'),
    path('get_rpki_trends/', bgp_monitor.get_rpki_trends, name='get_rpki_trends'),
    path('bgp-monitor/', views.bgp_monitor_page, name='bgp_monitor_page'),
   

    
   # /monitor/api/get-bgp-stats/

]

userprofile/urls.py
from django.urls import path, include 
from . import views
app_name = 'userprofile'
urlpatterns = [
    path('saveProfile', views.saveProfile, name='saveProfile'),
    path('<str:username>', views.userprofile, name='userprofile')
]

monitor/models.py
from django.db import models

class Router(models.Model):
    name = models.CharField(max_length=100)
    ip_address = models.GenericIPAddressField()
    rpki_status = models.CharField(max_length=50, default='unknown')  # Status: configured, not_configured, disabled

    def __str__(self):
        return self.name

monitor/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.http import require_GET
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.db import IntegrityError
from django import forms
import psycopg2
import json
from .connections import test_ssh_connection, generate_router_id, extract_routers_details, process_router_details, fetch_router_status_and_time
from .bgp_stats import get_bgp_peers_count, get_total_prefixes_count_latest, fetch_bgp_summary_all_routers
import requests
from django.shortcuts import render
import paramiko
import logging,time

@csrf_exempt
def delete_router(request):
    try:
        data=json.loads(request.body.decode('utf-8'))
        router_id = str(data.get('routerId'))
        conn = psycopg2.connect(
                    database="bgpmonsec",
                    user="bgpmonsec_user",
                    password="admin",
                    host="127.0.0.1",
                    port="5432"
                )   
        cursor = conn.cursor()

        cursor.execute('DELETE FROM public."ROUTERS_INPUT" WHERE router_id=%s',(router_id,))
        conn.commit()
        cursor.close()
        conn.close()
        

        # Definește comanda SQL de inser
        
        return JsonResponse({'message': '200 Router Deleted Successfully!'})
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)
    

@csrf_exempt
def modify_router(request):
    try:
        data = json.loads(request.body.decode('utf-8'))
        router_id = str(data.get('routerId'))
        ip = data.get('ip')
        username = data.get('username')
        password = data.get('password')
        description = data.get('description')

        print(data)

        conn = psycopg2.connect(
            database="bgpmonsec",
            user="bgpmonsec_user",
            password="admin",
            host="127.0.0.1",
            port="5432"
        )
        cursor = conn.cursor()
        cursor.execute(
            'UPDATE public."ROUTERS_INPUT" SET "IP" = %s, username = %s, password = %s, description = %s WHERE router_id = %s',
            (ip, username, password, description, router_id)
        )
        conn.commit()
        cursor.close()
        conn.close()

        return JsonResponse({'status': 'success', 'message': 'Router modified successfully!'})
    except Exception as e:
        return JsonResponse({'status': 'error', 'message': str(e)}, status=500)
    
def show_routers_details(request):
    # Execută un query SQL pentru a prelua toate datele din tabel
    r_details = extract_routers_details()
    data_routere = [{'IP': row[0].split(',')[0].replace("(",""),'description': row[0].split(',')[1], 'r_state': row[0].split(',')[2], 'router_id': row[0].split(',')[3].replace(")","")} for row in r_details]
    # Transmite datele către șablon
    return JsonResponse(data_routere, safe=False)




@csrf_exempt
def salveaza_datele(request):
    if request.method == 'POST':
        try:
            # Extrage datele din corpul cererii
            data = json.loads(request.body.decode('utf-8'))
            ip = data.get('ip')
            username = data.get('username')
            password = data.get('password')
            description=data.get('description')

            # Afișează datele în consola server-ului Django
            print(f"IP: {ip}, Username: {username}, Parola: {password}, description: {description}")
            if test_ssh_connection (ip,username,password) == 200:
                print ('SSH connection successful!')
                router_id=generate_router_id()
                r_state=str('active')
                # Conectează-te la baza de date PostgreSQL
                conn = psycopg2.connect(
                    database="bgpmonsec",
                    user="bgpmonsec_user",
                    password="admin",
                    host="127.0.0.1",
                    port="5432"
                )   
                
                # Creează un cursor
                cursor = conn.cursor()
                # Definește comanda SQL de insert
                sql_insert = 'INSERT INTO public."ROUTERS_INPUT" ("IP", username, password, description,r_state,router_id) VALUES (%s, %s, %s, %s, %s, %s);'
                #INSERT INTO public."ROUTERS_INPUT" (IP, username, password) VALUES ('192.168.10.1', 'admin', 'admin');
                # Execută comanda SQL folosind parametrii
                cursor.execute(sql_insert, (ip, username, password,description,r_state,router_id))
                # Salvează modificările
                conn.commit()

                # Închide cursorul și conexiunea
                cursor.close()
                conn.close()
                return JsonResponse({'status': 'success'})
            else:
                return JsonResponse({'status': 'error', 'message': f'SSH CONECTION FAILED:'})
        except json.JSONDecodeError as e:
            return JsonResponse({'status': 'error', 'message': f'Eroare la decodificarea JSON: {str(e)}'})
    else:
        return JsonResponse({'status': 'error', 'message': 'Metoda de cerere nu este POST'})

@login_required
def monitor(request):
    return render(request, 'monitor/monitor.html', {'titlu': 'MONITORIZARE RETEA'})

@csrf_exempt
def configure_rpki(request):
    if request.method == 'GET':
        return render(request, 'monitor/configure_rpki.html', {'titlu': 'RPKI CHECK'})
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            router_id = data.get('router_id')
            ip_address = data.get('ip_address')
            asn = data.get('asn')

            if not router_id or not ip_address or not asn:
                return JsonResponse({'status': 'error', 'message': 'Missing router_id, ip_address, or ASN'})

            conn = database_connection()
            cursor = conn.cursor()
            cursor.execute('SELECT username, password FROM public."ROUTERS_INPUT" WHERE router_id = %s', (router_id,))
            router = cursor.fetchone()

            if not router:
                return JsonResponse({'status': 'error', 'message': 'Router not found'})

            username, password = router

            ssh = paramiko.SSHClient()
            ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
            ssh.connect(ip_address, username=username, password=password)

            # Debug command

            # Use invoke_shell for interactive commands
            shell = ssh.invoke_shell()
            shell.send("conf t\n")
            shell.send(f"router bgp {asn}\n")
            shell.send("bgp rpki server tcp 192.168.62.129 port 3323 refresh 300\n")
            shell.send("end\n")
            shell.send("wr\n")
            time.sleep(2)
            output = shell.recv(9999).decode("ascii")
            print(f"Shell output:\n{output}")
            ssh.close()

            # Check if configuration was successful
            if "bgp rpki server" in output:
                return JsonResponse({'status': 'success', 'message': 'RPKI configured successfully'})
            else:
                return JsonResponse({'status': 'error', 'message': 'Failed to configure RPKI. Check router logs.'})

        except Exception as e:
            return JsonResponse({'status': 'error', 'message': str(e)})
    else:
        return JsonResponse({'status': 'error', 'message': 'Invalid request method'})

@login_required
def monitorizare_retea(request):
    return render(request, 'monitor/monitor.html', {'titlu': 'MONITORIZARE RETEA'})

@login_required
def bgp_stats(request):
    return render(request, 'monitor/bgp-stats.html')
    
def router_uptime(request, router_id):
    status, time_info = fetch_router_status_and_time(router_id)
    return JsonResponse({'status': status, 'time_info': time_info})

@login_required
def router_statistics(request, router_id):
    return render(request, 'monitor/router_statistics.html', {'router_id': router_id})

def router_details(request,router_id):
    r_details=process_router_details(router_id)
    return JsonResponse(r_details)

@login_required
def rpki_servers_stats(request):
    return render(request, 'monitor/rpki-servers.html', {'titlu': 'RPKI SERVER STATUS'})

@login_required
def alerts_page(request):
    return render(request, 'monitor/alerts.html', {'titlu': 'ALERTS'})

@login_required
def bgp_monitor_page(request):
    return render(request, 'monitor/bgp_monitor.html')  

@require_GET
def get_bgp_stats(request):
    fetch_bgp_summary_all_routers()
    num_peers = get_bgp_peers_count()
    num_prefixes_ipv4 = get_total_prefixes_count_latest()

    data = {
        'num_peers': num_peers,
        'num_prefixes_ipv4': num_prefixes_ipv4,
    }
    return JsonResponse(data)

import requests
from django.http import JsonResponse

def fetch_rpki_data(request):
    url = "http://192.168.62.129:8323/status"
    try:
        # Preia datele de la serverul RPKI
        response = requests.get(url)
        response.raise_for_status()
        text_data = response.text

        # Parsează datele
        lines = text_data.split('\n')  # Împarte datele pe linii
        parsed_data = {}

        for line in lines:
            # Ignoră liniile goale și comentariile
            if line.strip() and not line.startswith('//'):
                # Împarte linia pe baza primului ":"
                if ':' in line:
                    key, value = line.split(':', 1)  # Împarte doar pe primul ":"
                    parsed_data[key.strip()] = value.strip()

templates/monitor/alerts.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RPKI Check</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>

<header>
    <a>Alerts</a>
</header>

<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a href="/monitor/monitor" class="navbar-brand">
        <img src="{% static 'logo.png' %}" alt="Logo" style="height: 50px;">
    </a>

    <ul class="col-xs-4 navbar-nav mx-auto">
        <li class="nav-item"><a href="/monitor/bgp-stats" class="nav-link">BGP Statistics</a></li>
        <li class="nav-item"><a href="/monitor/rpki-servers-stats" class="nav-link">RPKI Servers</a></li>
        <li class="nav-item"><a href="/monitor/configure_rpki" class="nav-link">RPKI CHECK</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Link 4</a></li>
    </ul>
    
    <button id="alertButton" class="btn btn-warning" onclick="redirectToAlertsPage()" style="position: relative; background-color: transparent; border: none;">
        <div id="alertTriangle" style="width: 0; height: 0; border-left: 15px solid transparent; border-right: 15px solid transparent; border-bottom: 25px solid grey; position: relative;"></div>
        <span id="alertCount" style="position: absolute; top: -5px; right: -10px; background-color: red; color: white; font-size: 12px; border-radius: 50%; padding: 2px 5px; display: none;"></span>
    </button>
    <a>"   "</a>
    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img src="{% static 'default.png' %}" alt="User Icon" style="width: 20px; height: 20px;">
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{% url 'userprofile:userprofile' request.user %}">View My Profile</a>
            <a class="dropdown-item" href="/changepass">Change Password</a>
            <a class="dropdown-item" href="/handlelogout">Log Out</a>
        </div>
    </div>
</nav>
<div class="container mt-5">
    <h2>Alerts</h2>
    <button class="btn btn-primary" onclick="markSelectedAlertsAsRead()">Mark as Read</button>
    <table class="table table-striped">
        <thead>
            <th>
                <input type="checkbox" id="selectAllCheckbox" onclick="toggleAllCheckboxes(this)">
            </th>
            <tr>
                <th></th>
                <th>Router ID</th>
                <th>Alert Type</th>
                <th>Alert Name</th>
                <th>Description</th>
                <th>Timestamp</th>
            </tr>
        </thead>
        <tbody id="alertsTable">
            <tr>
                <td colspan="6" class="text-center">Loading alerts...</td>
            </tr>
        </tbody>
    </table>
    
</div>

<script>

function formatTimestamp(timestamp) {
    const date = new Date(timestamp);
    const options = { 
        day: '2-digit', 
        month: 'short', 
        year: 'numeric', 
        hour: '2-digit', 
        minute: '2-digit', 
        hour12: false 
    };
    return date.toLocaleString('en-US', options);
}
    async function fetchAlerts() {
    const response = await fetch('/monitor/get_alerts/');
    const data = await response.json();

    const alertsTable = document.getElementById('alertsTable');
    alertsTable.innerHTML = ""; // Curăță tabelul

    if (data.status === 'success') {
        const alerts = data.alerts;

        if (alerts.length === 0) {
            alertsTable.innerHTML = `<tr><td colspan="6" class="text-center">No alerts found</td></tr>`;
        } else {
            alerts.forEach(alert => {
                const row = alertsTable.insertRow();
                row.style.backgroundColor = alert.was_readed === 'false' ? 'red' : 'white';
                row.style.color = alert.was_readed === 'false' ? 'white' : 'black';

                // Checkbox pentru selectare
                const checkboxCell = row.insertCell(0);
                const checkbox = document.createElement('input');
                checkbox.type = 'checkbox';
                checkbox.value = alert.ID; // ID-ul alertei
                checkboxCell.appendChild(checkbox);

                // Detalii alertă
                row.insertCell(1).innerText = alert.router_id;
                row.insertCell(2).innerText = alert.alert_type;
                row.insertCell(3).innerText = alert.alert_name;
                row.insertCell(4).innerText = alert.description;
                row.insertCell(5).innerText = formatTimestamp(alert.timestamp); // Folosește funcția de formatare
            });
        }
    } else {
        console.error('Error fetching alerts:', data.message);
    }
}

    async function markSelectedAlertsAsRead() {
        const checkboxes = document.querySelectorAll('#alertsTable input[type="checkbox"]:checked');
        const alertIds = Array.from(checkboxes).map(checkbox => checkbox.value);

        if (alertIds.length === 0) {
            alert('Please select at least one alert.');
            return;
        }

        const response = await fetch('/monitor/mark_alerts_as_read/', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ alert_ids: alertIds })
        });

        const data = await response.json();
        if (data.status === 'success') {
            alert('Selected alerts marked as read');
            fetchAlerts(); // Reîncarcă tabelul
        } else {
            console.error('Error marking alerts as read:', data.message);
        }
        fetchUnreadAlertsCount();
    }

    // Încarcă alertele la deschiderea paginii
    fetchAlerts();

    async function fetchUnreadAlertsCount() {
        const response = await fetch('/monitor/get_unread_alerts_count/');
        const data = await response.json();

        if (data.status === 'success') {
            const count = data.count;
            const alertTriangle = document.getElementById('alertTriangle');
            const alertCount = document.getElementById('alertCount');

            if (count > 0) {
                alertTriangle.style.borderBottomColor = 'red';
                alertCount.style.display = 'inline';
                alertCount.innerText = count;
            } else {
                alertTriangle.style.borderBottomColor = 'grey';
                alertCount.style.display = 'none';
            }
        } else {
            console.error('Error fetching alerts:', data.message);
        }
    }

    // Apelează funcția periodic pentru actualizarea alertelor
    fetchUnreadAlertsCount();
    setInterval(fetchUnreadAlertsCount, 15000);

    function redirectToAlertsPage() {
        window.location.href = '/monitor/alerts/';
    }

    function toggleAllCheckboxes(source) {
    const checkboxes = document.querySelectorAll('#alertsTable input[type="checkbox"]');
    checkboxes.forEach(checkbox => {
        checkbox.checked = source.checked;
    });
}
</script>

templates/monitor/bgp-stats.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BGP Statistics</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>
<header>
    <a>BGP Statistics</a>
</header>
<body>
 <!-- Navigation -->
 <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <a href="/monitor/monitor" class="navbar-brand">
        <img src="{% static 'logo.png' %} " alt="Logo" style="height: 50px;">
    </a>


    <ul class=" col-xs-4 navbar-nav mx-auto">
        <li class="nav-item"><a href="/monitor/bgp-stats" class="nav-link">BGP Statistics</a></li>
        <li class="nav-item"><a href="/monitor/rpki-servers-stats" class="nav-link">RPKI Servers</a></li>
        <li class="nav-item"><a href="/monitor/configure_rpki" class="nav-link">RPKI CHECK</a></li>
        <li class="nav-item"><a href="/monitor/bgp-monitor" class="nav-link">BGP Attacks Monitor</a></li>
    </ul>
    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <img src="{% static 'default.png' %}" alt="User Icon" style="width: 20px; height: 20px;">
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="{% url 'userprofile:userprofile' request.user %}">View My Profile</a>
            <a class="dropdown-item" href="/changepass">Change Password</a>
            <a class="dropdown-item" href="/handlelogout">Log Out</a>
        </div>
    </div>
  </nav>
  <br>
 <div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="stat-card">
                <div class="icon">👥</div>
                <div class="value" id="num-peers">Loading...</div>
                <div class="description">Număr de Peers</div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="stat-card">
                <div class="icon">🌐</div>
                <div class="value" id="num-prefixes-ipv4">Loading...</div>
                <div class="description">Număr de Prefixe IPv4</div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8">
            <h3>Peer Data</h3>
            <table class="table table-bordered" id="peer-table">
                <thead>
                    <tr>
                        <th>Prefix</th>
                        <th>ASN</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
        <div class="col-md-4">
            <h3>Top Peers (Prefixes Received)</h3>
            <ul class="list-group" id="top-peers-list"></ul>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <h3>IPv4 CIDR Prefix Count</h3>
            <canvas id="prefixChart"></canvas>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>


var prefixChart; // Declare the chart variable outside the function

function fetchBGPStats() {
    $.ajax({
        url: '/monitor/api/get-bgp-stats/',
        method: 'GET',
        success: function(data) {
            $('#num-peers').text(data.num_peers);
            $('#num-prefixes-ipv4').text(data.num_prefixes_ipv4);
        },
        error: function() {
            $('#num-peers').text('Error');
            $('#num-prefixes-ipv4').text('Error');
        }
    });
}

$(document).ready(function() {
    // Lista tuturor măștilor de rețea posibile
    var allMasks = ['8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32'];

    function fetchBGPStats() {
        $.ajax({
            url: '/monitor/api/get-bgp-stats/',
            method: 'GET',
            success: function(data) {
                $('#num-peers').text(data.num_peers);
                $('#num-prefixes-ipv4').text(data.num_prefixes_ipv4);
            },
            error: function() {
                $('#num-peers').text('Error');
                $('#num-prefixes-ipv4').text('Error');
            }
        });
    }

    function fetchBGPPeers() {
        $.ajax({
            url: '/monitor/api/get-unique-prefixes/',
            method: 'GET',
            success: function(data) {
                var peerTableBody = $('#peer-table tbody');
                peerTableBody.empty();
                
                data.prefixes.forEach(function(prefix) {
                    peerTableBody.append(
                        '<tr>' +
                            '<td>' + prefix.network_with_mask + '</td>' +
                            '<td>' + prefix.as_number + '</td>' +
                        '</tr>'
                    );
                });

                // Generate chart data
                var cidrCounts = {};
                // Inițializează cidrCounts cu toate măștile posibile la 0
                allMasks.forEach(function(mask) {
                    cidrCounts[mask] = 0;
                });

                data.prefixes.forEach(function(prefix) {
                    var cidr = prefix.network_with_mask.split('/')[1];
                    if (cidrCounts[cidr] !== undefined) {
                        cidrCounts[cidr]++;
                    }
                });

                var labels = allMasks;
                var dataCounts = labels.map(function(label) {
                    return cidrCounts[label];
                });

                createChart(labels, dataCounts);
            },
            error: function() {
                console.error('Error fetching BGP peers data');
            }
        });
    }

    function createChart(labels, dataCounts) {
    var ctx = document.getElementById('prefixChart').getContext('2d');
    if (window.prefixChart) {
        window.prefixChart.destroy();
    }
    window.prefixChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: ['/8', '/9', '/10', '/11', '/12', '/13', '/14', '/15', '/16', '/17', '/18', '/19', '/20', '/21', '/22', '/23', '/24', '/25', '/26', '/27', '/28', '/29', '/30', '/31', '/32'],
            datasets: [{
                label: 'Prefix Count',
                data: dataCounts,
                backgroundColor: 'rgba(75, 192, 192, 0.2)',
                borderColor: 'rgba(75, 192, 192, 1)',
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                x: {
                    barPercentage: 0.7, // Adjust this value as needed
                    categoryPercentage: 0.7, // Adjust this value as needed
                    ticks: {
                        maxRotation: 40, // Rotate the labels if needed
                        minRotation: 40 // Rotate the labels if needed
                    },
                    grid: {
                        display: false // Hide grid lines on x-axis
                    }
                },
                y: {
                    beginAtZero: true,
                    grid: {
                        display: false // Hide grid lines on y-axis
                    }
                }
            }
        }
    });
}

    // Apelăm funcțiile la fiecare 30 si 25 de secunde
    setInterval(fetchBGPPeers, 25000);
    setInterval(fetchBGPStats, 30000);

    // Apelăm funcțiile imediat ce pagina se încarcă
    fetchBGPStats();
    fetchBGPPeers();
});
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>